### ISSUE TITLE
oh god

### ISSUE THREAD

**Issue by garnetluvcookie** [Explosion-Scratch/Muahahaha#2]

**Comment by Explosion-Scratch** [comment]
XD

**Comment by Explosion-Scratch** [comment]
I pinned it because that's what needed to happen.

**Comment by devxan** [comment]
@Explosion-Scratch This is beautiful. Really annoying on the GitHub homepage.

**Comment by ghost** [comment]
> @Explosion-Scratch This is beautiful. Really annoying on the GitHub homepage.

Yes, it's very disturbing

**Comment by ghost** [comment]
@Explosion-Scratch Is this like Chinese written vertically or something?

**Comment by ghost** [comment]
> @Explosion-Scratch Is this like Chinese written vertically or something?


No, it's a fictional language called Zaglo.

**Comment by devxan** [comment]
🤣

**Comment by ghost** [comment]
@AmpersandGD Zaglo or [Zalgo](http://www.eeemo.net/)?

**Comment by ghost** [comment]
Zalgo

**Comment by javascript-programmer** [comment]
lol XD  wierd writing
